### PR TITLE
Add PG-TO-252-3-313 from Infineon

### PR DESCRIPTION
**Pull request by pointhi**
source: http://www.infineon.com/dgdl/PG-TO252-3-313-Package_Overview.pdf?fileId=5546d462580663ef015806c94cf509cd

pg-to-252-3-313

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... but I found two things:
1. the big pad should move 0.2mm up -(10.6-2.2/2-6.4/2)=-6.3 (you had -6.1)
2. What about making the Fab-layer a bit more detailed, i.e. showing the metal pad4: 
to252

Best,
JAN

**Comment by SchrodingersGat** [comment]
Also if this is a footprint specific to Infineon, please prepend `Infineon_` to the footprint name. Thanks @pointhi

**Comment by jkriege2** [comment]
Hi @pointhi 

How does this differ from the existing TO-252 (smaller pads?):
2017-04-24 20_08_14-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

PS: Are you still on this? If so, please fix KLC-issues!

Best,
JAN

**Comment by ghost** [comment]
Hi @pointhi 

Since Jan posted that screenshot on 24 April, the TO-252 2 lead footprint has changed. Would this cover the Infineon requirement?

image

**Comment by evanshultz** [comment]
@hackscribble Good find! This exactly matches the Infineon footprint.

@pointhi Unless there is something I've missed, this footprint exists. I'll close this case in 2 days unless you object.

**Comment by evanshultz** [comment]
Seems fixed some time in the past. Closing case.

**Pull request closed without merging**
