### PR TITLE
DIP-6_SMD plus DIP-4_SMD in three different versions

### PR DESCRIPTION
**Pull request by evanshultz**
Created the 4-pin gullwing SMT footprint for a DIP package, then two variants with other lead spacing. The footprints are designed to match with the packages for the VO615A family of optocouplers shown on page 6 of the datasheet: http://www.vishay.com/docs/81753/vo615a.pdf.

All KLC steps pass expect for 10.7 since I haven't made a 3D model.

The names are rather ugly and suggestions on a better naming scheme are desired. I haven't yet discovered a similar situation in an existing library to guide me towards a proper package name.

### CODE REVIEW

**Comment by evanshultz** [comment]
Here are images of the footprints:
image

**Comment by evanshultz** [comment]
And for completeness, here is the six pin version.

**Comment by jkriege2** [comment]
Hi!

Comments on these devices (BTW: Thanks ... I was already thinking about adding them  myself ;-)

0. Please resubmit these footprints to `Housings_DIP.pretty`
1. The footprints are missing a F.FAB-layer
2. Please fix the positions of the labels
3. Can you provide some drawing for these packlages/footprints from a datasheet (for the review)? THat would be great.
4. Please draw silkscreen as for the other DIP-packages, e.g.:
2016-12-20 21_46_05-footprinteditor keine aktive bibliothek

Best,
JAN

**Comment by evanshultz** [comment]
Thank you, Jan!

0. Duh! My mistake. However, the similar DIP-8_SMD footprint is in SMD_Packages. Where is the correct location for this style of footprint?
1. None of the DIP footprints (in Housings_DIP) I see have this, so I used KLC 6.9 as a guideline.
2. Where should they go? KLC doesn't mention location and the default modules are inconsistent.
3. Sure! Vishay VO615A is mentioned above and a DIP-6_SMD example is [H11L1](https://www.fairchildsemi.com/datasheets/H1/H11L1M.pdf). (They aren't exactly 6/8 of each other so we may need to generalize.)
4. As mentioned in #0, I copied the style from the existing DIP-8_SMD. Which one is best for KiCad?

**Comment by jkriege2** [comment]
- ad 0) I would put them in Housings_DIP. Could you also provide the 8-pin version and we can delete it from SMD_packages? ... It seems that the latter is a place to collect anything old that has not yet been resorted ... and a more systematic approach seems good to me ;-)
- ad 1),2) yes those footprints are quite old ... the lib is largely not yet conforming to KLC! I would go for a footprint that looks somehow like that (just a quick sketch ... e.g. pads are much better in yours):
2016-12-21 18_10_40-footprinteditor keine aktive bibliothek
Note how the F.Fab represents the outline of the package itself ... maybe for the one with winges pins one can even draw the pins here.
- ad 3) those are way sufficient ;-) ... just something to check against
- ad 4) the more KLC-conformant the better ;-)

Best,
JAN

**Comment by jkriege2** [comment]
Maybe if I have some time over christmas, I can also try and rework all the other DIPs to match KLC ...

**Comment by evanshultz** [comment]
0. Of course. Is there a way to do this without destroying this PR and creating a new one? Since the .pretty libs are all different repos, I don't know how. I can do it, it's just that the conversation gets spread around. Maybe resolve all issues here and then I'll move them as the last step?
2. Fixed
4. Small tweaks here and there in the patch above. I haven't yet done the pin 1 indication on fab or silk.

Note that I'm working up a DIP-8_SMD as well and will submit it with the patch in the correct lib later.

**Comment by evanshultz** [comment]
I really dislike the extra long line for pin 1 indication on THT parts. For SMT parts where silk lines are already there (like SOT-363), it's doesn't bother me.

Most often I see a marking in the silk outline or a dot, and in mind it would be better to hew more closely to a traditional convention rather than doing something unique and, to me, easier to miss. I Googled "silkscreen pcb pin 1" and picked out these examples: [dot inside and outside silk](https://s3.amazonaws.com/s3-blogs.mentor.com/tom-hausherr/files/2011/05/figure-1-example-of-silkscreen-ref-des.png), [dot outside silk](http://blog.optimumdesign.com/hs-fs/hub/317720/file-1497273534-png/Figure_79_Silkscreen_Markings_and_Cleanup.png?t=1475177744383&width=723&name=Figure_79_Silkscreen_Markings_and_Cleanup.png), [notch in silk corner and dot inside](https://s3.amazonaws.com/s3-blogs.mentor.com/jimmartens/files/2014/11/SS_blog_1.jpg), [silk box under body](http://public.iorodeo.com/docs/electrophoresis_power_supply/_images/image_7.JPG), [notch in outline](http://farm3.static.flickr.com/2726/4421548319_75f95de1a2.jpg), [notch in silk outline and "1" text](http://www.diyforums.org/Doodlebug/construction/graphics/Step01.gif), [different pad 1 shape](https://cdn.sparkfun.com/assets/learn_tutorials/4/0/1/DIP-pin-1_2.png), [notched silk corner under part](http://ecee.colorado.edu/ecen3000/labs/finalproject/files/front.png), [doubled silk line under part](https://s-media-cache-ak0.pinimg.com/236x/b5/3d/83/b53d838fa97d62fb3ea1c1db1f0064bd.jpg), [break in silk outline](http://www.pcblibraries.com/forum/uploads/5603/3.png), and on and on and on... But those are amateur and professional boards that may or may not adhere to any standard.

So let's try to find a standard. IPC-7351 (no suffix), starting on page 65, shows the following:
- Dot inside silk body outline
- Dot outside silk body outline
- Notched corner of silk body outline

Also good info starting on page 13 of the [IPC-7351C goals](http://www.ipc.org/committee/drafts/1-13_d_7351CGoals.pdf).

I'm sure there's more info out there. And I may be a fool. (Probably, not may...) I'm on board with the silk line for SMT parts, but for THT parts where there's more room I think it behooves KiCad to take advantage of that room by making a bigger and more obvious pin 1 indication.

My criteria is the following:
1. What is the standard? This is likely to be common to many CAD tools and thus familiar.
2. What is best for KiCad users, both designers and those working with the resulting PCBs?

I don't mean to turn this PR into a big discussion or war, but KLC isn't clear on pin 1 marking style and I want to bring up the topic. No change happens without thought. Thanks everybody!

**Comment by jkriege2** [comment]
Hi!

This discussion seems to get a bit broader. So I tried to make some possible designs for DIP-packages ... The SMDs should simply have other pads. The current DIP-footprints are not so nice (IMHO), because they waste a lot of space at the top and bottom between the silkscreen-line and the actual package (which is in addition missing on F.FAB).

Different possible styles for DIP:
2016-12-25 14_28_30-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

Silkscreen-only:
2016-12-25 14_30_07-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

I personally would use maybe a mixture of styles 2/3 AND 5 then the pin1 marking is visible after assembly (IEC). ALso I would maybe make pin1 a rectangular pad. For me this is more graphic when assembling (there is a full box), but still meets the IEC requirements (visible after assembly, pin1) and only violates the requirement to not be under the component partly.

But we should get more opinions on this ( @SchrodingersGat @pointhi @CarlPoirier @diggit  ... what do you think? )

Best,
JAN

**Comment by evanshultz** [comment]
Thanks for accepting my comments and putting this together!

I like styles 2 and 3 (or a double bar on the short side similar to style 2), but would also like to see a dot outside the package. I dislike styles 1 and 5. Style 4 seems OK to my fundamentally, but I'd dismiss it since it's more common on SMT footprints and not THT.

In addition, making pin 1 square is also a nice and common pin 1 mark.

**Comment by evanshultz** [comment]
Also, consider PCBs with no silkscreen. In this case, making DIP/SIP footprints have a unique pin 1 shape is critical. While it may not apply to the DIP_SMD parts we're discussing here, to me it's critical to making KiCad all it can be.

**Comment by SchrodingersGat** [comment]
Hey @evanshultz  @jkriege2 great discussion here thus far. I would that pin-1 indication should occur on *all* three of:

* Pin 1 (should be square)
* Silkscreen
* Fab Layer

I would propose a slightly different style as below:

untitled

* Pin-1 square as noted above
* Silkscreen is reduced to match the actual dimensions of the package.
* Inner portion of silkscreen will *not* be visible **after** assembly, but is visible for assisting with hand-assembly.
* Orientation of package is noted on Silkscreen
* Orientation is marked on F.Fab using 1mm bevel as per IPC standard

What do you guys think of this? I think it encompasses all the requirements as above.

Also, the silkscreen should be removed from the pads. The DIP packages currently have that option set for the pads, this should be changed.

**Comment by SchrodingersGat** [comment]
And also, these should (as @jkriege2  has suggested) go in the https://github.com/KiCad/Housings_DIP.pretty lib

**Comment by SchrodingersGat** [comment]
Regarding file naming, I would put the _SMD as a suffix to the part name e.g. **DIP-4_9.53mm_SMD**

**Comment by jkriege2** [comment]
Hi @evanshultz !

I'm currently preparing a script that generates the DIP-packages ... and can also generate the SMD-packages, all in a nice and KLC-conforming style. OK for you? Here are some examples (I'll note the PR, when done!):
2016-12-27 12_31_04-footprinteditor keine aktive bibliothek
2016-12-27 12_31_43-footprinteditor keine aktive bibliothek

2016-12-27 12_44_33-footprinteditor keine aktive bibliothek

2016-12-27 12_43_33-footprinteditor keine aktive bibliothek
2016-12-27 12_44_07-footprinteditor keine aktive bibliothek

**Comment by jkriege2** [comment]
Hi!

OK, I made a PR that should also contain your packages ... please check!

https://github.com/KiCad/Housings_DIP.pretty/pull/3

best,
JAN

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Housings_DIP.pretty/pull/3 has been merged. Thanks for the great work.

**Pull request closed without merging**
