### PR TITLE
Rename DRT-3

### PR DESCRIPTION
**Pull request by evanshultz**
This is a proprietary Texas footprint, from what I see. So give it a vendor prefix.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks :)

**Comment by jkriege2** [comment]
Did you also change the footprint fields and FPFilters linkng to this?

JAN

**Comment by evanshultz** [comment]
@jkriege2 Thanks for thinking of places where things could break. I only found it used by TPD2EUSB30/TPD2EUSB30A, and yes I did with https://github.com/KiCad/kicad-library/pull/1478. If I missed anything please let me know.

**Comment by SchrodingersGat** [comment]
Might be a good idea to have a script that searches for all symbols that reference a given footprint. When I have some time I'll add such a feature to [this script](https://github.com/KiCad/kicad-library-utils/pull/138)

**Pull request merged**
