### PR TITLE
Create SOT-665 and SOT-666

### PR DESCRIPTION
**Pull request by evanshultz**
Example datasheets:
http://www.nxp.com/documents/data_sheet/PESDXL4UF_G_W.pdf (SOT-665)
http://www.nxp.com/documents/data_sheet/PESDXL5UF_V_Y.pdf (SOT-666)

Footprint images:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
They all fail KLC 10.7 because there is no 3D file.

SOT-665 fails 6.4, ostensibly because the 5-pin package appears to be "unbalanced" with respect to the footprint origin.

**Comment by evanshultz** [comment]
Add pin 1 indication

**Comment by jkriege2** [comment]
Hi!

nice work.

Please change this:
1. Move Silkscreen from below the footprint
2. please make F.Fab 0.1mm thick.

Thanks,
JAN

**Comment by evanshultz** [comment]
Thanks for the review.

1. The silk is 2mm apart and 0.1mm thick. So 1.9mm ignoring real-world imperfections. The datasheets above show the part body width to be 1.7mm wide max. So the silk is outside the body, I believe. Am I in error with my math or understanding?
2. Oops! Done.

**Comment by jkriege2** [comment]
Hi!

ad 1) I think then the F.Fab rectangle is simply a bit too wide! It should be 1.3x1.7mm² just like the actual package. Also you can reduce the width of the Courtyard a bit:
2016-12-23 12_39_35-footprinteditor keine aktive bibliothek


cu
JAN

**Comment by evanshultz** [comment]
I fixed the F.Fab size and shrunk the courtyard on top and bottom, but on the sides it appears to be 0.25mm away from the pad edge already. All good?

**Comment by jkriege2** [comment]
looks good, only for SOT-665 the Courtyard on the rhs is a bit farther (~0.4mm) than the required 0.25mm from the pads.

Could you fix that? Then I'll merge!

Best,
JAN

**Comment by evanshultz** [comment]
Aaah, gotcha. Fixed!

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
