### PR TITLE
Create SOT-363.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Based on latest update to SOT-353 footprint.

### CODE REVIEW

**Comment by evanshultz** [comment]
Here is the image:
image

**Comment by evanshultz** [comment]
Fails KLC 10.7 because no 3D file.

If this PR is merged, PR #19 should be closed since they appear to be duplicates but mine is closer to the master trunk with the SOT-353 footprint.

**Comment by evanshultz** [comment]
Added silk line for pin 1.

**Comment by jkriege2** [comment]
Hi!
 nice addition. First, one question:
Are SOT-363 and SC-70-6 the same? If so ... could you also update the SC-70-X packages with your (better) drawing (and variants)? ... This PDF indicates that: http://www.onsemi.com/pub_link/Collateral/419B-02.PDF
Otherwise this one looks fine!

About the DIP-4 devices: Those should go to `Housings_DIP.pretty`. Still some review before you resubmit them there:
1. The footprints are missing a F.FAB-layer
2. Please fix the positions of the labels
3. Can you provide some drawing for these packlages/footprints from a datasheet (for the review)? THat would be great.

Best,
JAN

Best,
JAN

**Comment by jkriege2** [comment]
Ahhh ... OK; I just saw your PR https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/29 ... So please just remove the DIP-4's from this PR.

Best,
JAN

**Comment by evanshultz** [comment]
DIP packages deleted. Sorry. I don't know what I was thinking.

Regarding the footprints, our SC70-6 vs SOT363 conversation is in another PR.

**Comment by jkriege2** [comment]
First copy of reply from @evanshultz  to the issue above:

> 
> Interesting. The SOT363 given by [NXP](http://www.nxp.com/documents/outline_drawing/SOT363.pdf) is quite a bit different. Long thin pins are replaced by square ones. [Central Semi](https://www.centralsemi.com/PDFs/case/SOT-363PD.PDF). [Vishay](http://www.vishay.com/docs/84015/sot363.pdf). [Diodes Inc](http://www.diodes.com/_files/packages/SOT363.pdf).
> 
> Here's one from [Linear Tech](http://cds.linear.com/docs/en/packaging/SOT_6_05-08-1638.pdf) that doesn't match either of those two. [Fairchild ](http://www.icbank.com/icbank_data/semi_package/sc706_dim.pdf)is different. So is [Vishay](http://www.vishay.com/docs/72602/72602.pdf).
> 
> Are they all compatible? Probably, but they're not the same footprint. The component package is virtually identical in all cases.
> 
> So it seems to me this is manufacturer-specific. What to do? I can make any changes that's best for KiCad.

**Comment by jkriege2** [comment]
I went a bit through the datasheets you linked ... basically the packages seem to have the same size of around (2-2.2)mm*(1.3-1.4)mm  ... all within the MIN/MAX-ranges given there. The pds however are different:
1. Most have a width of 0.4-0.5mm
2. The length varies bewteen 0.5mm and 1mm ... 

So I would do a compromise: pads should be 0.65*0.4mm² as that covers most and then add a special symbol `_HandSoldering` or `_LargePads` with pads 1*0.5mm² ... What do you think? 

Also many DSs call this SOT-363 and SC-70-6 in parallel, so I would simply make one design and save it as two footprint files (with the variants each). Then from that it would be great if you could also rework the fewer pin variants (at least of SC-70).

OK with you?
JAN

**Comment by evanshultz** [comment]
Jan,

Personally, I think a single footprint should be OK. If KiCad includes a usable footprint then it should be OK even if it's not quite the same as the manufacturer specifies. I can often tell which CAD package was used when looking at a PCB, but even with those variations between each CAD package it still works.

With that in mind, I changed to 0.65mmX0.4mm pads on SOT-363. How does that look?

I'm happy to update the footprints with fewer pins if this is good with you.

**Comment by jkriege2** [comment]
Looks good to me, so go ahead! ... BTW: Great work :-)))

JAN

**Comment by jkriege2** [comment]
Hi!

Like in this PR: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/28 please ensure that the package on the F.Fab has the right dimension!

Best,
JAN

**Comment by evanshultz** [comment]
Hi Jan,

The F.Fab outline is 1.35x2.2mm. That's right in the range of the datasheet package sizes. What dimensional change were you thinking about?

I did notice that the courtyard wasn't quite 0.25mm away from these longer pads, so I moved it slightly.

**Comment by jkriege2** [comment]
Was just a note to double-check ;-)
JAN

**Comment by jkriege2** [comment]
OK.

I think the SOT-363 is complete and ready to be merged. So will you add some more variants (SC70, fewer pins, ...) to this PR, or should I merge and we do it separately?

Best,
JAN

**Comment by evanshultz** [comment]
Variants added, except replicating the _Handsoldering variant of SC-70-6. That one would be rotated 90 degrees to match with SOT-363 as a seed file. Is that OK?

**Comment by evanshultz** [comment]
Also, I didn't do the normal SC-70 since it has bigger pins and a different style.

**Comment by evanshultz** [comment]
I realized the normal SC-70* were rotated, so I went ahead and did the _Handsoldering one.

Assuming it's OK to rotate those parts for consistency's sake, I think something needs to happen to make the footprint and the 3D model align (the same rotation). I can see this in the kicad_mod file but I'm not familiar with how to manipulate the rotation to make them match. Do you know? I'm looking at it.

**Comment by jkriege2** [comment]
Rotation is fine to me and footprints look good!
Please recreate the 3D model sections from the old models ... you'll maybe have to set Z-Rotation to 90°:
2016-12-26 10_04_18-footprint eigenschaften
2016-12-26 09_59_58-footprint eigenschaften

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 What are you using to view these footprints? I have little experience using the 3D tools in KiCad, but I suspect it's another tool you're using.

Also, there are a number of PRs which seem related to this one. Let me enumerate them below and provide a proposed resolution:
- #6: Remove the 5- and 6-pin parts of this PR as they're covered here @WillBickerstaff 
- #19: Close it @bseishen
- #21: Add 4-pin version here using the format above and close this PR @SchrodingersGat 

If everyone is OK with the above, I'll add SC-70-4 to this PR and then the last two can be closed. I'll also add a comment to PR #6.

**Comment by jkriege2** [comment]
Just go ahead and We will notify the other contributors as required ... I have the feeling that your PR is the only one that's currently really active!

cu
JAN

PS: To view the footprints I usually use the 3d viewer of KiCAD: open the footprint (or a PCB) and hit `ALT+3`

**Comment by SchrodingersGat** [comment]
I have closed my PR https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/21

**Comment by jkriege2** [comment]
Hi!

looks good mostly. I was wondering a bit about the SC70-4. I found two types of packages online, 
1. one with pin2 a bit wider (~0.6mm instead of ~0.3mm): http://datasheets.maximintegrated.com/en/ds/MAX4785-MAX4788.pdf ... this version looks like SOT-143 (which we have already) and which has pin1 wider.
2. seldomly a version with all pins with the same width (as in your version): http://www.tayloredge.com/reference/Packages/packages/umd4.jpg

I think version 1 is more common, so maybe have the current version as `SC-70-4_allPinsSmall` and add a second `SC-70-4` with the wider pad 2. Also that package should be there a second time as SOT-343 (http://www.produktinfo.conrad.com/datenblaetter/150000-174999/153161-da-01-en-TRANSISTOR_RF_BFP405_SOT_343__INF.pdf).


In addition: would you also provide an SC-70-3 (http://www.vishay.com/docs/71153/71153.pdf) which is currently available simply as `SC-70` (i.e. update that one)? Then we have all of the SC-70s ;-)

BTW: Rest looks good and if you don't have time to make the 3-pin-version I will merge after the 4-pin stuff is corrected!

Best,
JAN

**Comment by evanshultz** [comment]
Hi Jan!

Good points all around. To further muddy the waters, it seems some vendors use a different pinout for their SOT-343. See https://www.centralsemi.com/PDFs/case/SOT-343PD.PDF and http://www.nxp.com/assets/documents/data/en/package-information/98ARH98309A.pdf and http://pdf2.datasheet.su/avago%20technologies/mga-52543-blkg.pdf. What do we do with that? I think that at some point we have to merge this commit and add other footprints as needed.

Here's another example of SOT-343 (they also call it SC-82-4) with 4 equal-size pins: http://www.micro-bridge.com/data/EMP/EMP8734.pdf.

Do you have a recommended program to create 3D models? [FreeCAD](http://freecadweb.org/) would seem to idealogically be a good match to use with KiCad, but it doesn't mention wings/wrl support.

**Comment by evanshultz** [comment]
Oh, and I'd like to finish off the 4-pin parts here and do teh 3-pin in a separate PR if you don't mind.

**Comment by jkriege2** [comment]
Hi!

1) 3-pin in separate PR: OK!
2) For 3D I use FreeCAD ... WINGS is not really needed anymore by KiCAD, so I usually omit it. WRL-export works fine, see e.g. https://github.com/KiCad/kicad-library/pull/797 https://github.com/KiCad/kicad-library/pull/868
3) Also please add a pin1-mark to F.Fab, e.g.:
2017-01-10 12_21_24-footprint editor no active library
2017-01-10 12_22_41-footprint editor no active library

4) About the SOT-343 ... mhhh... what do you think of this (SC-70-$-variants accordingly):
  - make `SOT-343_AllPinsSmall` with all pads small: 2017-01-10 12_07_51-footprint editor no active library
  - make `SOT-343` with pad2 big:2017-01-10 12_09_16-footprint editor no active library
  - make `SOT-343N` (for name see: http://www.nxp.com/packages/SOT343N) with pad1 big:
2017-01-10 12_15_22-footprint editor no active library

**Comment by SchrodingersGat** [comment]
Pin-1 indication should use the 1mm bevel on the top-left corner:

81a42d9a-d72f-11e6-9727-5a8b1b5ae4a5

Regarding part naming, I would use *SOT-343* for the footprint with all pads small (all pins the same size). Then for each version that has a larger pad, I would indicate that pad in the name.

e.g. `SOT-343-LargePad2`

What do you think?

**Comment by jkriege2** [comment]
Hhmmm ... 
1) Bevel is fine with me (although I would not require 1mm as the package is only 1.35*2.25mm² ;-)
2) naming: I'm not sure ... it seems to me that the "standard" SOT-343 (i.e. the one used the most, see [infineon](http://www.infineon.com/dgdl/SOT343-Package_Overview.pdf?fileId=5546d462580663ef015806a5338d04ef) [broadcom](https://docs.broadcom.com/cs/Satellite?blobcol=urldata&blobheader=application%2Fpdf&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadername3=MDT-Type&blobheadervalue1=attachment%3Bfilename%3DAV02-0672EN-DS-ATF-58143-08Jun20120.pdf&blobheadervalue2=application%2Fx-download&blobheadervalue3=abinary%253B%2Bcharset%253DUTF-8&blobkey=id&blobnocache=true&blobtable=MungoBlobs&blobwhere=1430855955370&ssbinary=true) [infineon](http://www.infineon.com/dgdl/Infineon-BFP640-DS-v02_00-EN.pdf?fileId=db3a30431400ef6801142747c1a1071d) [centralsemi](https://www.centralsemi.com/PDFs/case/SOT-343PD.PDF) (although with diferent numbering) [ONsemi](http://www.onsemi.com/pub_link/Collateral/NCP553-D.PDF) [Maxim](https://datasheets.maximintegrated.com/en/ds/MAX6711-MAX6713Z.pdf) [GMT](http://www.gmt.com.tw/product/datasheet/EDS-9091.pdf) [AME](http://www.ame.com.tw/datasheet/AME8503.pdf) [HP](http://www.hp.woodshot.com/hprfhelp/4_downld/products/xrs/hbfp0405.pdf) ) has pin2-large, so I would use that one as the one without addendum, as people will expect that one. Also a package with no pin wider will fit onto the standard footprint! The one with pad1-large (SOT-343N above) seems also to be known as SOT-143: [AME](http://www.ame.com.tw/datasheet/AME8503.pdf) [google-pic-search](https://www.google.de/search?client=firefox-b-ab&biw=1543&bih=832&tbm=isch&sa=1&q=SOT-143&oq=SOT-143&gs_l=img.3..0i19k1.157756.157756.0.158453.1.1.0.0.0.0.100.100.0j1.1.0....0...1c..64.img..0.1.99.UJUNSWMj0f0) or SOT-343R: [NXP](http://www.nxp.com/assets/documents/data/en/data-sheets/MBC13916.pdf)

So let's sum up;
1) pin2-large `SOT-343`
2) pin1-large `SOT-143` and/or `SOT-343R`
3) all small: `SOT-343_allPinsEqual` (or so)

Best,
JAN

**Comment by evanshultz** [comment]
Thanks for the input, all.

My concern with this is that some vendors name the pins differently. So if pin 1 is the lower left, some vendors will use pin 1 and the large one and some have pin 2 as the large one. So any default footprint named `SOT-343`, even if the majority of parts use it, would be an incorrect default in some cases.

I favor keeping all small pads as the standard footprint and adding a suffix to the footprint name for parts which have one larger pad, indicating the pad name. Any specific part which has one large pad could use the Footprint Field on the symbol to explicitly select the matching footprint from the library.

In KiCad we can keep a consistent numbering convention, starting from the lower left with pin 1 and increasing counter-clockwise around the package. This is typical for most ICs and makes footprint numbering consistent for KiCad users. Specific parts may deviate as desired and can link the symbol to a specific footprint for user simplicity.

My preference matches @SchrodingersGat but is different than you, @jkriege2. I do want to get this finished and merged so I'll willing to do something different, but I want to reach a consensus.

**Comment by SchrodingersGat** [comment]
1. I strongly think that we should have SOT-343 as "standard" with large-flag pins as alternatives.
2. Are we going to remove the SC-70 parts, and replace them with the SOT-xxx equivalents? If we do:
a) We should add the 'SC-70-x' PN to the description
b) We should go through all symbols in kicad-library and replace all references to SC-70-x

**Comment by jkriege2** [comment]
1. anyway you like ;-)
2. I proposed to have them ALSO, merely as copy of the SOT-343 ... an alternative would be to have somethink like `SOT-343_SC-70-4` as footprintname ... That's how e.g. Pentawatt and TO-220-5 are implemented

**Comment by SchrodingersGat** [comment]
I like the idea of appending the `SC-70-x` part name, rather than duplicating the parts.

**Comment by evanshultz** [comment]
I like having all package names available. Since KiCad separates logical and physical domains of a part, removing any valid package names seems worse for the user.

It seems like the above discussion to concatenate the package names would require us to change the footprint name and FPLIST for every library part currently using this package. Is that correct?

**Comment by jkriege2** [comment]
About changing the FPFilters: Only if they don't match the combined new name, e.e. if the new name ist `SOT-343_SC-70-4` then the stdnard `SOT?343*` will still work, but `SC?70*` not ...

**Comment by evanshultz** [comment]
I'm OK with that. In which order should the packages be listed? `SC-70` first or `SOT-343` first? Once I get this I'll make a summary of the changes, unless one of you guys wants to do it, and then make the changes.

**Comment by jkriege2** [comment]
`SOT`-first?

**Comment by evanshultz** [comment]
OK, so this is what I see we will end up with:
- [x] `SOT-363_SC-70-6`
- [x] `SOT-353_SC-70-5`
- [x] `SOT-343_SC-70-4`
- [x] `SOT-363_SC-70-6_Handsoldering`
- [x] `SOT-353_SC-70-5_Handsoldering`
- [x] `SOT-343_SC-70-4_Handsoldering`

What do you think about the SOT-143* footprints? Are they good as they are and users will have to figure out to use that footprint if the datasheet says SOT-343 (or some variant)? Or should we do something like `SOT-143_SOT-343`, `SOT-143R_SOT-343`, etc.

And another small note: Why do the reverse SOT-143 have both `R` and `_Reverse`? Seems they're tied together so does it really require having both pieces of info to indicate reverse pin direction?

All parts will have a fab rectangle with pin 1 bevel. In addition, the following need it as well:
- [ ] HVSOF5
- [ ] SOT-23-*
- [ ] SOT-543
- [ ] SOT-553
- [ ] SOT-665
- [ ] SOT-666
- [ ] SOT-886
- [ ] SOT-89*
- [ ] TSOT-6*
- [ ] VSOF5

Thanks for all the time to think through this and improve the library in the best interest of KiCad!

Also, any idea how to update the necessary symbols' FPLIST? I believe it's just symbols that contain footprints starting with `SC`.

**Comment by jkriege2** [comment]
Sounds all good to me ... usually I update such things semi-automatedly using Notepad++, which can serach/replace in files ... For the SOT-143 I would leave it just as such ...

Best,
JAN

**Comment by evanshultz** [comment]
Also check that line widths are all correct in this lib as @jkriege2 found SOT-23 is 0.15mm for fab lines on SOT-23 (https://github.com/KiCad/Diodes_SMD.pretty/pull/28).

**Comment by jkriege2** [comment]
here it looks good!

**Comment by jkriege2** [comment]
all footprints check out OK

**Comment by evanshultz** [comment]
Added/renamed the SOT-3x3_SC-70-x footprints.

I also added the pin 1 bevel to only the normal 4-pin part. Review would be appreciated even though it's far from done. I see dots, bevels, and no marking on the existing footprints in TO_SOT_Packages_SMD so if we go with bevel and this is good I'd modify all outstanding footprints to use a bevel and add in a fab rectangle if it's missing.

**Comment by jkriege2** [comment]
Hi!

I'm just looking through this a last time.
- For some reason I cannot open `SOT-343_SC-70-4.kicad_mod` ... please fix
- For some reason I cannot open `SOT-353_SC-70-5.kicad_mod` ... please fix
- For some reason I cannot open `SOT-363_SC-70-6.kicad_mod` ... please fix
- SC70: please move silkscreen from under the device

Best,
JAN

**Comment by evanshultz** [comment]
Thanks for the review, Jan!

SC-70 updated. I didn't add a bevel for parts with asymmetrical pins. Is that OK or should all have a bevel? If fab is always viewed with pads, then no need, but if the fab layer is intended to be viewed without pads then a bevel makes sense to me.

**Comment by evanshultz** [comment]
Also fixed the issue with SOT-3x3* parts. Onward!

**Comment by jkriege2** [comment]
Hi!

I went through the other packages and fixed several problems that are not adressed by your PR:
https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/33

Best,
JAN

**Comment by evanshultz** [comment]
Fixed line width and added pin 1 bevel on fab rectangle to all parts you didn't touch in #33. Please review and answer the question about SC-70 above. What have I missed? What still needs to be done?

I believe #6, #19, and #21 can be closed as referenced above.

**Comment by jkriege2** [comment]
I think about the bevel: there should be some type of pin1-marker in the F.Fab for sure (bevel or dot) ...

**Comment by jkriege2** [comment]
about the double-fixed stuff ... we will get that done properly ;-) ... depending on which one is merge first!

**Comment by evanshultz** [comment]
Agreed. Based on past discussions, I understand bevel is the desired choice for this type of package (at least) for KiCad. How about if I handle the parts in this PR and you do the same for yours? I have no time now but will be able to finish mine by the end of the weekend.

**Comment by jkriege2** [comment]
- SC-70 should have bevel/pin1 mark
- SOT-223 needs bevel
- SOT-323 needs bevel
- finally: Could you also add SC-70-8: http://cds.linear.com/docs/en/packaging/SOT_8_05-08-1639.pdf

Best,
JAN

**Comment by jkriege2** [comment]
About your comment: OK! ... fixed it in my PR already

**Comment by evanshultz** [comment]
- Added pin 1 bevels from above.
- SC-70 and SOT-323 are the same ([here](http://www.nxp.com/documents/outline_drawing/SOT323.pdf), [here](http://www.infineon.com/dgdl/SOT323-Package_Overview.pdf?fileId=5546d462580663ef015806a4458204d1), [here](http://www.onsemi.com/pub_link/Collateral/419-04.PDF)) so renamed SC-70 to SOT-323_SC-70
- Realized there was no SOT-323_SC-70_Handsoldering so I made it.
- Added SC-70-8 as SC-70-8 (I don't find anything with this package showing an equivalent "SOT-323" so not adding that to the footprint name).

I need to check this all thoroughly and review your PR as well. What do you see?

**Comment by jkriege2** [comment]
Hi!

looks nearly perfect ... What I still spotted:

SOT-323: there's a double-stroke on the lhs Silkscreen:
2017-01-23 23_20_03-footprint editor no active library

If that's fixed, I would merge your PR and then updtae mine accordingly. OK?
JAN

**Comment by evanshultz** [comment]
Fixed. Still need to:
- [x] Add SC-70-8_Handsoldering
- [x] Add pin 1 bevels on 3 pin SOT-23s
- [ ] Look at changing SOT-143* pin 1 silk mark to straight line style

**Comment by evanshultz** [comment]
Oh. You already got the SOT-143* parts. I don't see anything else. Are we ready to merge this and #33 (assuming the notes I made on your PR are fixed or don't need to be done)?

Just one thing: KLC 6.2 mentions the pad 1 location. In this lib some are bottom left and some are top left. OK to leave it as is or do they all need to be top left?

**Comment by jkriege2** [comment]
I would leave the pin1-position for now. I'll merge this now.

THanks for all the work you put in!!!

Best,
JAN

**Pull request merged**
