### PR TITLE
Added VSOF5 footprint

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
nic work already ... could you please add the following to fully conform with KLC:
1. please add the outline of the device on the F.Fab layer with a width of 0.1mm, which should include some kind of mark for pin1 (e.g. a small circle next to the pin, or some indication in the package itself)
2. please make sure that the Silkscreen is then not below the SMD package, but outside
3. Could you provide datasheet-links for the two packages? The HVSOF5 I found in the BD1020 datasheet, but the VSOF5???

Best,
JAN

**Comment by crackerizer** [comment]
Hi Jan, all the changes you requested has been made. Here is the link to the datasheet I used to create the footprint. http://rohmfs.rohm.com/en/products/databook/package/spec/ic/vsof5_hvsof5_hvsof6_hson8-1-2-tr-e.pdf

**Comment by jkriege2** [comment]
Hi!

thanks. for the changes. some minor things still:
1. The pin1-mark should also be on the f.Fab layer and not below the SMD part (otherwise the part may not lie flat on the PCB due to the silkscreen!)
2. I would suggest to mark pin1 on the silkscreen simply by an elongated left line:
hsov

Also please note the 0.25mm clearance of the Courtyard to the package/pads and its width of only 0.05mm:

> Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.

So it's also maybe a bit too far from teh device on theleft/right in my sketch above (I measured clearance to the SilkSCreen!)

Could you still change thos? I already merged the temperature sensor https://github.com/KiCad/kicad-library/pull/789 that requires this package.

Best,
JAN

**Comment by crackerizer** [comment]
Hi Jan, I have made the changes. Check it out.

**Comment by jkriege2** [comment]
Great Work!
Thanks,
JAN

**Comment by crackerizer** [comment]
Thanks!

**Pull request merged**
