### PR TITLE
Added SOT23W

### PR DESCRIPTION
**Pull request by Misca1234**
Here is SOT-23W
from 
http://www.allegromicro.com/~/media/Files/Datasheets/A112x-Datasheet.ashx?la=en&hash=7BC461E058CC246E0BAB62433B2F1ECA104CA9D3

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

just had a quick look: pins are too wide apart in x-direction (is 1.4mm, but should be 1.2mm). Also the body is too wide: it should be 1.92x2.98mm²

Best,
JAN

**Comment by Misca1234** [comment]
Mmmm the effect of working late
I added the handsoldering as well

bild

bild

**Comment by jkriege2** [comment]
please enlarge the courtyard of the handsoldering ... it should be 0.25mm offset from the PAD and package outline.

Thanks,
JAN

**Comment by jkriege2** [comment]
Also the silkscreen-lines for the "normal" version are too long and the courtyard is too wide.

Please fix?

JAN

**Comment by jkriege2** [comment]
Also please draw the silkscreen as in the normal SOT-23, i.e. around the corners, pin1-silkscreen elongated
2017-08-19 09_54_20-footprint editor no active library

Best,
JAN

**Comment by Misca1234** [comment]
Like this 

bild

bild

**Comment by jkriege2** [comment]
yes, now only the courtyard needs fixing. It should surround the footprint with 0.25mm clearance to the F.Fab drawing and the pad outline (whichever is farther outside .. I think you can use the check_kicad_mod.py script with `--fixmore` if you delete the existing courtyard beforehand. It will draw an appropriate courtyard rectangle for you.

Best,
JAN

**Comment by Misca1234** [comment]
bild

bild

**Comment by jkriege2** [comment]
Great Work!
JAN

**Pull request merged**
