### PR TITLE
Added SOT-23-6_Handsoldering footprint

### PR DESCRIPTION
**Pull request by swalense**
This pull request proposes to add a handsoldering variant of the SOT-23-6 footprint extending the pad length towards the outside of the package by .5mm on each side.

The existing SOT-23-6 footprint has 1.06mm pads positioned at 1.1mm, thus making the overall footprint 3.26mm wide. Given that parts can extend up to 3mm (with tolerances) adding .5mm gives a bit of room when soldering by hand.

Please let me know if you believe this to be useful; or if .5mm is considered too small.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

It's great but you need to add the courtyard! Please have a look at the KiCad LIbrary Convention in the Wiki for more information.

Thanks!

**Comment by swalense** [comment]
Hi,

Thanks for the feedback! I have added the courtyard with .25mm clearance from pads on left/right and from the body on top/bottom. To avoid having the pin 1 indication on top of the courtyard line I moved the former a bit towards the outside.

Note that the courtyard was missing because there is none in the existing SOT23-6 footprint. Do you want me to align the SOT23-6 with this one once it is approved? (in another pull request)

**Comment by SchrodingersGat** [comment]
Thanks @swalense

**Comment by CarlPoirier** [comment]
Hi @swalense,

If you can volunteer for fixing the other footprints that would be much appreciated.

Regards,

Carl

**Comment by swalense** [comment]
Hi @CarlPoirier,

No problem, I will do that when I have a bit of spare time.

Eric

**Pull request merged**
