### PR TITLE
Fix TO-263-3Lead to be consistent with 5Lead version

### PR DESCRIPTION
**Pull request by openelectron**
Copied and renamed TO-263-3Lead to TO-263-3Lead-TabPin4

Edited existing TO-263-3Lead footprint so that tab is numbered pin 2.

This is now consistent with 5 pin version.

This issue was discussed here;
https://lists.launchpad.net/kicad-lib-committers/msg00269.html
I'm not sure a conclusive outcome was ever reached.

### CODE REVIEW

**Comment by openelectron** [comment]
Is there anything I can do to help get this merged?

**Comment by SchrodingersGat** [comment]
You have made two versions of the new footprint, with slightly different names:

TO-263-3Lead_TabPin4 (Keep this one)
TO-263-3Lead-TabPin4  (Delete this one)

**Comment by openelectron** [comment]
@SchrodingersGat I have removed the duplicate. Not sure where that came from.

**Comment by openelectron** [comment]
@SchrodingersGat  When you can I'd love to get this merged or make changes if it needs them.

Thanks

**Comment by SchrodingersGat** [comment]
Ah sorry @openelectron looks like I missed your last message way back in July.

Only one change that I can see - I would suggest using the SAME 3D model for the variant, even though this violates the KLC rule. There's no point requiring a duplicated model for this as there is no change to the model or the footprint, only the pinout.

**Comment by openelectron** [comment]
@SchrodingersGat  Updated as requested.
Rob.

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
