### PR TITLE
preparing for new 3d models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by Shackmeister** [comment]
decided to leave the anchor "uncentered" since the footprint is stupid
http://www.nxp.com/documents/outline_drawing/SOT665.pdf

**Comment by SchrodingersGat** [comment]
@Shackmeister is this ready for merge?

**Comment by Shackmeister** [comment]
Yup

**Comment by SchrodingersGat** [comment]
And merged it shall be.

**Pull request merged**
