### PR TITLE
Added PG_HSOF-8-1 package

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Reference: http://www.infineon.com/cms/packages/SMD_-_Surface_Mounted_Devices/P-PG-HSOF/P-PG-HSOF-08-1.html

This PR adds the PG_HSOF-8-1 MOSFET package with stencil to the datasheet specifications.

There is also a version with THT vias for thermal relief

PCB Symbol:
hsof

And the resulting part in 3D view (note the stencil apertures)

pcb

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
As pins 2-8 (inclusive) are all connected internally, should I number the pads the same?

If I numbered the pads as:

1 - G (1)
2 - S (2-8)
3 - D (9)

Then the footprint would be usable with a wide range of already existing transistor symbols.

Thoughts?

**Comment by jkriege2** [comment]
I would renumber them that way ... they are all connected in the end ... and you only need 3 pins the ine symbol!

JAN

**Comment by jkriege2** [comment]
Please fix:
```
checking module: PG_HSOF-8-1
  Violating Rule 10.7
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
      Attribute solder_paste_margin == -0.1 != 0!

  Violating Rule 10.8
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
      3D model filename 'PG-HSOF-8-1' is different from footprint name 'PG_HSOF-8-1'!

  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': 7.1, 'x':
      -3.7}, 'width': 0.15, 'start': {'y': 7.1, 'x': -5.4}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': 7.1, 'x':
      -5.4}, 'width': 0.15, 'start': {'y': -7, 'x': -5.4}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': -4, 'x':
      5.4}, 'width': 0.15, 'start': {'y': 4, 'x': 5.4}, 'layer': 'F.SilkS'}).

  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.

checking module: PG_HSOF-8-1_ThermalVias
  Violating Rule 10.6
    Attributes is set to the appropriate value, see tooltip for more information.
      There are mode THT-pads (42) than SMD-pads (12), but the attribute is not set to 'pth', but 'smd'.
  Violating Rule 10.7
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
      Attribute solder_paste_margin == -0.1 != 0!

  Violating Rule 10.8
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
      3D model filename 'PG-HSOF-8-1' is different from footprint name 'PG_HSOF-8-1_ThermalVias'!

  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': 7.1, 'x':
      -3.7}, 'width': 0.15, 'start': {'y': 7.1, 'x': -5.4}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': 7.1, 'x':
      -5.4}, 'width': 0.15, 'start': {'y': -7, 'x': -5.4}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'end': {'y': -4, 'x':
      5.4}, 'width': 0.15, 'start': {'y': 4, 'x': 5.4}, 'layer': 'F.SilkS'}).

  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.05mm, different from 0.1mm.

```

**Comment by SchrodingersGat** [comment]
Updates made to match new KLC - the footprints have been greatly improved.

They are still throwing errors on 8.3 and 9.4 - this is due to the specific pad requirements for these footprints.

**Comment by jkriege2** [comment]
Also here: Bottom pad please.

Also: According to http://www.infineon.com/cms/en/product/packages/PG-HSOF/PG-HSOF-8-1/ The single pads towards the bottom should be 0.8mm wide, not 0.75mm!
3. Pin-numbering is strange ... pins 2-8 are connected. Wouldn't it make more sense to just have pins 1 (single at bottom left), 2 (connected pins at bottom) and 3 (big pad).

Also: Please rotate, so pin 1 is at top-left.

best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks for spotting that Jan - I have made those fixes.

**Comment by jkriege2** [comment]
Hi!

I'm on holidays until mid next week... will check this out then ;-)

Best,
JAN

**Comment by SchrodingersGat** [comment]
Happy holidays!

**Comment by jkriege2** [comment]
Nice Work!
JAN

**Pull request merged**
