### PR TITLE
Add DPAK, D2PAK and D3PAK footprints

### PR DESCRIPTION
**Pull request by ghost**
## Scope

Script-generated footprints for DPAK, D2PAK and D3PAK devices.  They replace some existing footprints in the repo and fill in gaps to give the following coverage:

- DPAK: 3 and 5 pin
- D2PAK: 3, 5 and 7 pin

There are three footprints for each of these five devices:

- tab connected to centre pin (same pin number)
- tab not connected to centre pin (different pin number)
- centre pin cut (tab takes centre pin number)

There is one further footprint for D3PAK: 3 pin, centre pin cut.

All the footprints have been generated with a split paste mask for the tab. This leads to KLC 8.3 error ("Some SMD pads have incorrect layer settings") due to the paste layer pads overlaid on the tab.

image
image
image

#### Footprints added **EDIT**

```
TO-252-2.kicad_mod
TO-252-3_TabPin2.kicad_mod
TO-252-3_TabPin4.kicad_mod
TO-252-4.kicad_mod
TO-252-5_TabPin3.kicad_mod
TO-252-5_TabPin6.kicad_mod
TO-263-2.kicad_mod
TO-263-3_TabPin2.kicad_mod
TO-263-3_TabPin4.kicad_mod
TO-263-4.kicad_mod
TO-263-5_TabPin3.kicad_mod
TO-263-5_TabPin6.kicad_mod
TO-263-6.kicad_mod
TO-263-7_TabPin4.kicad_mod
TO-263-7_TabPin8.kicad_mod
TO-268-2.kicad_mod
```
#### Footprints removed
```
SOT-404.kicad_mod
SOT-428.kicad_mod
SOT-428_Handsoldering.kicad_mod
TO-252-5-11.kicad_mod
TO-263-3Lead.kicad_mod
TO-263-3Lead_TabPin4.kicad_mod
TO-263-5Lead.kicad_mod
```

In addition, the footprint `TO-252-2Lead.kicad_mod` has been renamed `TO-252-2Lead_Rectifier.kicad_mod`. This footprint has larger pads than the standard DPAK footprint. I think it may have been intended for rectifiers like this: http://www.griederbauteile.ch/download/Datasheet/Gehaeuse/TO-252.pdf

## Related PRs
Script: https://github.com/pointhi/kicad-footprint-generator/pull/36

## Datasheets
http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-3-1/
http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-5-11/
http://www.infineon.com/cms/en/product/packages/PG-TO263/PG-TO263-3-1/
http://www.infineon.com/cms/en/product/packages/PG-TO263/PG-TO263-5-1/
http://www.infineon.com/cms/en/product/packages/PG-TO263/PG-TO263-7-1/
http://www.icbank.com/icbank_data/semi_package/to268aa_dim.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@hackscribble these look really nice.

Can I suggest changing `-xLead` to `-x` e.g. `TO-252-2Lead` -> `TO-252-2`

* Closer match to industry "standard" naming 
* All of the footprints have this extraneous "Lead" so removing it does not reduce differentiation
* The word "lead" might not be as useful to non-english speakers

**Comment by SchrodingersGat** [comment]
Aside from this, my initial impressions are very favourable. I will find some time to look at them in detail.

**Comment by jkriege2** [comment]
PLease also add the DPAK, D2PAK,... string to the filenames (as done for the TO-251 IPAKs, e.g.: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/blob/master/TO-251-1EP_IPAK_Horizontal.kicad_mod ) ... This way one could use an FPFilter `*DPAK*` or `*D2PAK*` to match the footprints.

Best,
JAN

**Comment by jkriege2** [comment]
As a suggestion: Maybe add the pins at least as lines, or better as small rectangles to the F.Fab-layer

**Comment by ghost** [comment]
Thanks @SchrodingersGat and @jkriege2 

The naming was suggested by @evanshultz here: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/issues/46  Sorry, I should have linked to this in my original post.

So I think I need a ruling :wink: 

DPAK etc is on the keywords and description already.

But I will add the pin outline to Fab layer.

**Comment by SchrodingersGat** [comment]
> PLease also add the DPAK, D2PAK,... string to the filenames 

@hackscribble @jkriege2 I prefer the idea of having a single name for the footprints, rather than naming `FP-A_FP-B_FP-C`.

I would much rather we standardize on a single (most common) name for each footprint, as there can be multiple alternative names.

**Comment by SchrodingersGat** [comment]
And I would rule that the `Lead` should be removed ;)

**Comment by ghost** [comment]
So that would make them ...

```
TO-252-2                 (cut pin version of TO-252-3)
TO-252-3_TabPin2
TO-252-3_TabPin4
TO-252-5                 (cut pin version of TO-252-5)
TO-252-5_TabPin3
TO-252-5_TabPin6
etc
```
OK for me to go with this?

**Comment by jkriege2** [comment]
I second the removal of `Lead` ;-)

**Comment by jkriege2** [comment]
About the DPAK-stuff; What is the most common name?

**Comment by ghost** [comment]
I have mostly seen the devices identified by `TO-*` or `SOT-*`, with `D*PAK` then mentioned in the description in the datasheet.  Less often, it is the other way round, with `D*PAK` as the main identifier.

**Comment by jkriege2** [comment]
So it's fine with me if you leave it out ...

cu
JAN

**Comment by jkriege2** [comment]
PS: Can you also provide the scripts somewhere?

**Comment by SchrodingersGat** [comment]
I think name them TO-* and *add the D*PAK identifier to the keyword*

Hopefully keyword search for footprints (like there is for symbols) will be implemented soon.

**Comment by ghost** [comment]
> I think name them TO-* and add the DPAK identifier to the keyword*

OK, I will go with the naming in this comment ... https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/47#issuecomment-297322651

... and DPAK, DPAK-3, SOT-nnn etc are in the keywords.

> PS: Can you also provide the scripts somewhere?

Yes, I'll be submitting it to https://github.com/pointhi/kicad-footprint-generator and will link to it above.

Will post new images when I have added the pins to Fab layer.

**Comment by ghost** [comment]
Footprints updated with new naming convention and pins added to Fab layer.

Example:
image

**Comment by jkriege2** [comment]
Nice look ;-)

**Comment by jkriege2** [comment]
Did you base you scripts on the stuff I contributed to pointhi's tool for the THT-TOs?
JAN

**Comment by ghost** [comment]
> Did you base you scripts on the stuff I contributed to pointhi's tool for the THT-TOs?

I used some previous scripts I had written for Molex connectors as my starting point.  Then moved parameters for devices and vairants to a YAML config file.  I want to do more work on the program: use classes, move some code into functions for readability.

**Comment by jkriege2** [comment]
I started assembling a set of useful functions there:
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/tools

and here are the scripts I used for the THT variants:
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/TO_SOT_THT

Maybe some of that stuff can be of use for you!

**Comment by ghost** [comment]
Thanks, Jan :smile:  I will look through those links.

**Comment by pointhi** [comment]
@hackscribble,

when you like using .yaml files for specification (which I appreciate), there is already support for it in my framework included. (But not really documented now)

There is a implementation using it which could help you to understand it's behaviour:
* https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Resistors_SMD
* https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/general/smd_chip.py

It supports yml and csv as input, typechecks, optional parameters and exposes some command-line options to create example .yml and .csv files which then can be filled with values.

**Comment by ghost** [comment]
Thanks @pointhi I will look at how to use that in my script.

**Comment by jkriege2** [comment]
Hi!
this is script-generated. Right?

If so, could you also generate the very similar ATPAK package? See http://www.onsemi.com/pub/Collateral/ENA2192-D.PDF

Best,
JAN

**Comment by ghost** [comment]
@jkriege2 Will do.

**Comment by ghost** [comment]
Added `ATPAK-2.kicad_mod` to PR.

image

**Comment by jkriege2** [comment]
@hackscribble  @SchrodingersGat @pointhi I think  this can be merged ... any final thoughts? If not I would merge this PR this afternoon/evening

JAN

**Comment by jkriege2** [comment]
Nice work!

JAN

**Pull request merged**
