### PR TITLE
Texas_R-PDSO-G6 added

### PR DESCRIPTION
**Pull request by alitekin2fx**

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @aliteke79 Thanks for adding the footprint.  I won't be able to properly review until Sunday, but I noticed one thing.  Even though you are not submitting a 3D model, please add 3D details to the footprint.

See KLC item 10.4 https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

**Comment by ghost** [comment]
Hi @aliteke79 Thanks for submitting the footprint. I won't have time to review until Sunday.

There is a warning coming up in the Travis CI checks about missing 3D model details.  I know you may not be submitting one, but details need to be added anyway to avoid having to come back to change the footprint in future.  

In this case, I will check whether this footprint can simply reference the existing SC-70-6 3D model.

**Comment by alitekin2fx** [comment]
Hi @hackscribble, SOT-363_SC-70-6.wrl looks not bad. But Travis gives an error when i use an existing wrl file. Maybe we need to clone the 3D file.

**Comment by ghost** [comment]
Let me check that model too.  I think this exception in the KLC FAQ could apply here: https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions#klc-warns-about-incorrect-3d-model-name

**Comment by Shackmeister** [comment]
If it would be more appropriate with a seperate model I can generate one for you

**Comment by alitekin2fx** [comment]
I don't know guys, you can tell me what i do. It is written that a warning would be generated in the documentation but i get an error message for the naming difference.

**Comment by ghost** [comment]
Thanks @Shackmeister :smile:

The existing model is pretty close. (Discussion about how Texas footprint differs from typical SC-70-6 is in this PR: https://github.com/KiCad/kicad-library/pull/1375)

image

Body dimensions are spot on for the middle of the tolerance range in the Texas datasheet.  The span of the pins is a little below the middle of the range (1.8 - 2.4mm).



I guess trade-off is between accuracy vs increasing the size of the library / your time @Shackmeister :wink:

**Comment by Shackmeister** [comment]
Well when making most of the other models the hardest part was actually finding a proper datasheet :p

**Comment by ghost** [comment]
Hello @aliteke79  just a few minor changes and then I think this will be ready to merge.

1. The pad location coordinates are correct.  The pad size (0.85mm x 0.35mm) is smaller than what's shown in the datasheet for the copper pads.  They should be 0.9mm x 0.4mm. See "pad geometry" in the bottom left drawing.

image


2. Rotate the Fab layer reference so that it is vertical in the "portrait" shape of the device outline.  Also reduce the font size a little so that `REF**` fits within the outline.

image

3. Set silkscreen line width to 0.12mm.

4. In Footprint properties, set Documentation field to the comma-separated list:
`R-PDSO-G6, http://www.ti.com/lit/ds/slis144b/slis144b.pdf`

5. Set Keywords to space-separated list `R-PDSO-G6 SC-70-6`.

**Comment by alitekin2fx** [comment]
Hi @hackscribble. I have changed the problems except silkscreen line width, it looks like already 0.12mm.

**Comment by ghost** [comment]
Thanks for the contribution @aliteke79 

The line thickness was indeed right to begin with, sorry about that :blush:

**Comment by alitekin2fx** [comment]
You're welcome :)

**Pull request merged**
