### PR TITLE
adding DRT-3, SOT-1333-1, SOT-1334-1, SOT-963

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi @jeromebeguin,

Your footprints are very nice. I have only one comment. The SOT-1333 and SOT-1334 need the pin 1 marker on the F.Fab layer (KLC 7.4.ii.c) like you did for the SOT-963. Once you fix this we can merge.

Regards,

Carl

**Comment by jeromebeguin** [comment]
Hi @CarlPoirier 
actually the marker is there, the line is a bit longer along the pin 1. Maybe it's not visible enough.

**Comment by CarlPoirier** [comment]
Yes you have it on the silkscreen, but you also need it on the Fab layer.

Carl

**Comment by jkriege2** [comment]
@jeromebeguin The bevel is there in SOT-963, but is missing in DRT-3, SOT-1333-1, SOT-1334-1

**Comment by jeromebeguin** [comment]
Ah yes sorry. Now corrected.

**Comment by jkriege2** [comment]
Nice Work!

Thanks,
JAN

**Pull request merged**
