### PR TITLE
Add TO-220-7Lead_TabPin8 (aka TO-220-7-11)

### PR DESCRIPTION
**Pull request by ghost**
Relates to this symbol PR:
https://github.com/KiCad/kicad-library/pull/1186

image

### CODE REVIEW

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by lostwithouthope** [comment]
Hi there,

thx for your great work.
@hackscribble just wanted to point out that maybe it would be better that not the whole tap is on the cream layer for such packages.

cheers :)

**Comment by ghost** [comment]
Thanks @lostwithouthope - very good point!  You mean dividing the solder mask something like this?

image

I have updated the footprint and will submit a new PR.  Thanks for the catch!

image

**Comment by lostwithouthope** [comment]
@hackscribble exactly what I meant 👍

**Pull request merged**
