### PR TITLE
Correct 3D model location/scale/rotation

### PR DESCRIPTION
**Pull request by evanshultz**
Many models were not placed at 0,0,0, with a scale of 1,1,1, and a rotation of 0,0,0. This PR, as far as I can tell, corrects this for all models in this library.

Identified and discussed at https://github.com/KiCad/kicad-library/issues/1133.

Note! Any 3D models meant to properly match with the old location/scale/rotation would now be wrong. I've only correct the footprint side of it and checking the 3D models is a separate task (that I'm not volunteering for).

### CODE REVIEW

**Comment by evanshultz** [comment]
I think most of the Travis issues aren't a big deal, except for the 3D model names. Actually, some of the footprints are named oddly (like putting "_Housing" on SOT-89 parts). Once this is pulled, I promise to submit another PR that reviews footprint and 3D model names. But let's fix this first.

**Comment by evanshultz** [comment]
@jkriege2 @SchrodingersGat Certainly please use this PR to troubelshoot Travis, if required, and I'd also appreciate any feedback (if needed) or a merge. Thanks!

**Comment by SchrodingersGat** [comment]
I am not going to merge this until someone has fixed the 3D models - perhaps @easyw has some time as he is very good at it

The effort is appreciated but we can't break so many footprints without a fix in sight.

**Comment by Shackmeister** [comment]
I'll probably look into overhauling the rest of the SOT models over the next few weeks, but there is still some scripting to do to generate the missing models.. The ones already added was the ones I could actually generate. But I don't see any point in normalizing the settings before the new 3d models have been made

**Comment by Shackmeister** [comment]
Most of the models here have been corrected due to the new footprints so this should be closed

**Pull request closed without merging**
