### PR TITLE
Added TDSON-8-1 package

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Ref: http://www.infineon.com/cms/packages/SMD_-_Surface_Mounted_Devices/P-PG-TDSON/P-PG-TDSON-08-01x_2x_3.html

tdson

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
tdson

Footprint has been improved as follows:
- Added package outline to F.Fab layer
- Silkscreen improvements
- Added a _HandSoldering version with longer pads

**Comment by jkriege2** [comment]
looks good, mostly, please push to current KLC (e.g. 0.12mm SilkS, 0.1mm Fab):

```
checking module: TDSON-8-1
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': 3.6, 'x':
      -2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 3.6, 'x': -2.4}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': -3, 'x':
      -2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 3.6, 'x': -2.8}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': -2.6, 'x':
      2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 2.6, 'x': 2.8}}).

  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.

checking module: TDSON-8-1_HandSoldering
  Violating Rule 10.8
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
      3D model filename 'TDSON-8-1' is different from footprint name 'TDSON-8-1_HandSoldering'!

  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': 3.6, 'x':
      -2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 3.6, 'x': -2.4}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': -3, 'x':
      -2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 3.6, 'x': -2.8}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'start': {'y': -2.6, 'x':
      2.8}, 'width': 0.15, 'layer': 'F.SilkS', 'end': {'y': 2.6, 'x': 2.8}}).

  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
      Some fabrication layer line has a width of 0.15mm, different from 0.1mm.
```

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks for checking - KLC fixes have been made.

I have also rotated these parts so that Pin-1 is top-left

**Comment by jkriege2** [comment]
Hi!

a bit mean to already use the newer version of the scripts ... but I found some more ;-)

```
checking module: TDSON-8-1
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.

  Violating Rule 1.8
    Library files should use UNIX-style line-endings (LF)
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'height': 5.7, 'y': -2.85, 'x': -3.35, 'width': 6.7}
      was expected, but a courtyard rectangle {'height': 6.0, 'y': -3, 'x': -3.75, 'width': 7.5} was found

checking module: TDSON-8-1_HandSoldering
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.

  Violating Rule 10.8
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
      3D model filename 'TDSON-8-1' is different from footprint name 'TDSON-8-1_HandSoldering'!

  Violating Rule 1.8
    Library files should use UNIX-style line-endings (LF)
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'height': 5.7, 'y': -2.85, 'x': -3.5, 'width': 7.0} was
      expected, but a courtyard rectangle {'height': 6.0, 'y': -3, 'x': -3.75, 'width': 7.5} was found

```

Could you fix? Otherwise they look very nice to me.
JAN

**Comment by SchrodingersGat** [comment]
I think I have them fixed, but I'm not sure why the courtyard is giving an error?

**Comment by jkriege2** [comment]
That's one of my new functions: This check calculates the expected courtyard from the F.Fab outline and the pad-outside and then moves that 0.25mm (or the appropriate amount) outside. here the proposed change is due to the fact that the KLC (as I understood it) is soleily based on the F.Fab+pads and NOT on the silkscreen. But in your footprint, the courtyard surrounds the silkscreen ...

But we can also merge it the way it is.

JAN

PS: THere are some (invisible/doubled?) F.Fab-lines with 0.05mm width ...

**Comment by SchrodingersGat** [comment]
I have removed that extra line if ready to merge :)

**Comment by jkriege2** [comment]
The line is also there in the non-HandSOldering:
> ` (fp_line (start -3 -1.6) (end -3 -1.6) (layer F.Fab) (width 0.05))`

Could you fix that too?

About the courtyard-check: SHould we do this check differently? Or did I misinterpret a bit? E.g. I could extend the rect, so it just covers the F.Fab, even if that makes it larger ... or something like that. What do you think? We could also lower that to a warning (but then we need a mechanism to activate the fix separately, I think). A third possibility would be to allow say up to crt-offset deviation before there is an error, but then maybe only allowing for larger courtyards ...

Any ideas?
JAN

**Comment by SchrodingersGat** [comment]
I think that we should be cautious of implementing too much auto-fixing - this may be an instance where a simple "please add a courtyard" message is enough?

There are many varied options here, whereas other rules are easier to fix automatically. I will give it some thought.

**Comment by SchrodingersGat** [comment]
I have fixed that other line, too

**Pull request merged**
