### PR TITLE
Add TSOT-23*-packages and fix all remaining KLC-violations

### PR DESCRIPTION
**Pull request by jkriege2**
- I did not fix SC-70/SOT-353/363/... as these will be fixed by  https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/26
- added full set of `TSOT-23`-packages (3,5,6,8 pins)
- added missing `SOT-23-5_HandSoldering` variant
- added SOT-383FL (http://www.onsemi.com/pub_link/Collateral/ENA2267-D.PDF)
- added SOT-383F (http://www.mouser.com/ds/2/80/CPDVR085V0C-HF-RevB-10783.pdf)
- added `SOT-23-8`
- fixed KLC-issues of:
  - `HVSOF5`
  - `VSOF5`
  - `SOT-23`*
  - `SOT-89`
  - `PowerMacro_M234*`
  - `PQFN_8x8`
  - `SOT-404`
  - `SOT-428`
  - `TO-252`
  - `SOT-543`
  - `SOT-553`
  - `SOT-665`
  - `SOT-666`
  - `SOT-669`
  - `SOT-886`
  - `TO-263`
  - `TO-277A`
  - `TO-50`

sot-23-5_handsoldering
tsot23
tsot23_3d
2017-01-21 15_13_59-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-01-21 16_54_33-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-01-21 19_56_52-footprint editor no active library
2017-01-21 20_14_10-footprint editor no active library

### CODE REVIEW

**Comment by evanshultz** [comment]
Fabulous, Jan!

I haven't looked through it all but one thing: Does the description for PowerMacro_M234* need to differentiate between the parts? Right now they're named differently but the description appears to be identical.

Note that I touched some of the same parts, like SOT-323 and HVSOF5, in #26 so be sure to merge properly. :)

**Comment by evanshultz** [comment]
You do such great work!

I noticed a few things:
- The following have REF** on top and package name on bottom: HVSOF5, PQFN_8x8, VSOF5
- SOT-404, SOT-428*, SOT-886, TO-252*, TO-50-3* have text vertical
- The following have dots and not bevels for pin 1 on fab layer: HVSOF5, SOT-553, SOT-66*, SOT-89*, VSOF5
- The following are missing a pin 1 mark on the fab layer: SOT-404, SOT-428*, SOT-669*, SOT-886, TO-252*, TO-263*, TO-277*
- TSOT-6* appear to be removed; are they replaced by TSOT-23-6*? And also, TSOT-23* are the same as SOT-23* but they're just thinner, right? So different 3D models but no difference in footprints?

These are minor things and maybe not worth fixing. I don't know. Just bringing it up because if I look for consistency they popped out to me.

**Comment by jkriege2** [comment]
Hi!

so I merged in your changes ... About your comments:
1. TSOT-23 (yes renamed from TSOT-6 to TSOT-23-6 as that seems to be the correct package name) and SOT-23 also slightly differ in package size (TSOT>SOT):
2017-01-24 19_19_18-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2. I moved some REFDES on purpose to the left, so they are close to the silkscreen-line and moved away from the pads!
3. I did not put a pin1-mark when the sketch on F.Fab is unambiguous.


OK, I think this PR should be done ... @SchrodingersGat can you have a look, when you're back?
Best,
JAN

PS: @evanshultz ddn't you want to become a maintainer? Any progress?

**Comment by jkriege2** [comment]
@SchrodingersGat @diggit @pointhi could one of you have a look? This complements PR https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/26 by @evanshultz which was already merged!

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Hi Jan,

A couple of comments here:

a) Please observe the pin-1 on upper-left even for these components (most of these components need to be rotated 90 degrees CW)

e.g. from [this reference](http://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/Component%20Zero%20Orientations%20for%20CAD%20Libraries.pdf)

orientation

b) The SOT89-5_Housing footprint seems to be misaligned
untitled

Fine work as always - let's get the orientation issues sorted out :)

**Comment by jkriege2** [comment]
1. Most were already rotated (the ones that weren't are now ;-)
2. added HVSOF6:
2017-02-04 19_11_42-footprint editor no active library

**Comment by jkriege2** [comment]
PS: I modified our check-scripts to allow for rotations (on command-line request!): https://github.com/KiCad/kicad-library-utils/pull/77 ... and also fixed several rules therein!

**Comment by SchrodingersGat** [comment]
Jan these are really good additions, thanks :)

**Pull request merged**
