### PR TITLE
Courtyards review - Part 1

### PR DESCRIPTION
**Pull request by swalense**
Hi @CarlPoirier and all,

Following the discussion in pull request #14 I have already reviewed/added the courtyards for the components below.

The clearance is .25mm with respect to
- The pads defined in the existing footprint,
- And/or the maximum body dimensions in the package documentation, as IPC 7351 appears to measure the excess courtyard from the maximum boundary of the component.

Please let me know if these are ok. Afterwards I can continue with the rest of the TO SOT lib.

SOT-223
SOT-23 and SOT-23 handsoldering
SOT-23-5
SOT-23-6 and SOT-23-6 handsoldering
SOT-323
SOT-353

### CODE REVIEW

**Comment by pointhi** [comment]
The changes look good. I'm only a little bit unsure about SOT-223

**Comment by swalense** [comment]
Thanks for the feedback @pointhi .

Are you referring to the shape of the courtyard wrt. to the shape of the SOT-223?

In IPC-7351 the courtyard is defined as the "smallest rectangular area" (compared to e.g. "polygon" in IPC-7251 for THT), hence my choice. Although I have no particular knowledge of such standards (I'm usually on the software side of things ;-)), so my interpretation must be taken with a grain of salt.

**Comment by CarlPoirier** [comment]
Hi guys, sorry for not having seen this earlier.

Indeed, SOT-323 is a bit challenging since it's quite wrong in its actual state. First, the silkscreen doesn't follow rule 6.5. Second, the pads are too long. 0.6x0.8 should be a good compromise.

As for the courtyard, it would need to be smaller if you shorten the pads. SC-70 also has the pads wrong since they should be equivalent.

SOT-223 also has its silkscreen wrong. The pads smaller pads should be 1.5mm wide and the bigger one 3.8mm wide, but in the Y direction both are correct so the courtyard is great!

As for the rest, they are great.

Sources:

https://www.infineon.com/cms/packages/SMD_-_Surface_Mounted_Devices/SOT/SOT323_xSC70x.html
http://www.diodes.com/_files/zetex_files/pack/SOT323.pdf
http://www.onsemi.com/pub_link/Collateral/318E-04.PDF
http://www.diodes.com/_files/zetex_files/pack/SOT223.pdf

**Comment by swalense** [comment]
Hi @CarlPoirier, @pointhi,

I have committed a revision of the SOT-323. The pad size is adapted and it's rotated for better compliance with rule 6.2. The silkscreen is also redrawn to avoid overlaps (with a mark for pin 1 similar to e.g. the SOT-23-6).

**Comment by CarlPoirier** [comment]
The problem is that silkscreens like the SOT-23-6 don't have their outline completely visible after assembly. This is rule 6.5. They really should be like the SOT-23 or the SC-70-6_Handsoldering (minus the arrow which is a second pin 1 marker).

I know this is not clear at all because of the wrong examples in the library, I'm sorry.

**Comment by swalense** [comment]
Hi @CarlPoirier,

Sorry for the delay... I have reverted my previous commit on the SOT-323 to restart from the existing footprint (with courtyard) and to change the pad size and silkscreen in the same style as the SOT-23.

However I am not sure to understand your comment about the arrow as a second pin 1 marker? Do you mean that the angled silkscreen could be interpreted as marker for pin 1?

**Comment by SchrodingersGat** [comment]
I would suggest that as you are fixing up the courtyards for these parts, that the package outline should be added to the fabrication layer too!

**Comment by swalense** [comment]
Hi @SchrodingersGat,

Sure. I see that you've worked on that for the SSOP; I will have a look at it before.

**Comment by CarlPoirier** [comment]
Hi @swalense 

I meant that in the SC-70-6_Handsoldering footprint, there are two pin 1 indicators. There is the elongated silkscreen line on the left and then there is the angled silkscreen. The footprints don't need two markers, only the elongated line will suffice.

Carl

**Comment by swalense** [comment]
Hi,

My bad @CarlPoirier, my master was not up-to-date and was missing the silkscreen features you mentioned.

I have updated the SOT-323 as shown below,
- the package outline is added to the fabrication layer, following the max dimensions (I assumed that overlaps are ok as it is not meant to be printed);
- the silkscreen is updated to match the example in the IPC 7351C presentation [http://www.ipc.org/committee/drafts/1-13_d_7351CGoals.pdf]. However I'm unsure about the placement of the silkscreen... What does represent the "land gap" mentioned in the presentation? Is that the purple pad clearance in KiCad?

screen-capture-5

**Comment by SchrodingersGat** [comment]
@swalense the updated SOT-323 looks like a marked improvement. I would also suggest rotating so that pin-1 is top-left as per IPC recommendation for zero-rotation orientation. (This appears to be very inconsistent for this library).

**Comment by swalense** [comment]
Thanks @SchrodingersGat. I rotated it in the latest commit.

**Comment by swalense** [comment]
Similar treatment applied to the SOT-223.

But I'm still unsure about the placement of the silkscreen wrt. the package and/or pads. Please let me know if you have more info on this.

screen-capture-1

**Comment by SchrodingersGat** [comment]
Here's how IPC7351C recommends silkscreen for SOT footprints:
untitled

I would suggest following that. You're almost there, just need some extra silkscreen down the right hand side.

**Comment by CarlPoirier** [comment]
Hi @swalense,

Your changes are a great improvement. The SOT-223 and SOT-323 are perfect. [Edit: I hadn't seen @SchrodingersGat comment. Indeed, you could add the other silkscreen line on the single pad side] If you feel for it, please apply the same treatment to the other footprints!

Thank you very much,

Carl

**Comment by swalense** [comment]
Hi @CarlPoirier and @SchrodingersGat,

The latest push contains changes (with additions for the single pad) for all footprints already in the pull request (SOT-23, 23-5, 23-6, 223, 323 and 353 + existing handsoldering versions).

The pads in the SOT-353 are slightly enlarged (by ~.1mm in both directions) to match Zetex's layout. Also looking at the sheets from ON and NXP it appears that recommendations vary greatly, but the pad width in Kicad was still relatively small compared to these.

Similarly the length of the pad in the SOT-23 is increased by .1mm.

Concerning the rest, in summary:
- the package outline follows the maximum dimensions
- the silkscreen is aligned on the .05mm grid
- the silkscreen is placed on the package outline; except if that leads to a distance to pads lower than .15mm (which is my interpretation of the "silkscreen to land gap = line width" in the IPC presentation; see e.g. the SOT-23).

Eric

**Comment by CarlPoirier** [comment]
Hi @swalense,

First, sorry for the late review. Your fixes are great except that the silkscreen needs to be completely visible after assembly. Thus, it has to be a little offset with respect to the package outline. This one is perfect however. In the screenshot provided by @SchrodingersGat, it's not all that obvious because we see the actual package, so here's another one for you, this time for a QFN:

image

I'll try to monitor this closely so that we can get it merged soon.

Regards,

Carl

**Comment by swalense** [comment]
Thanks @CarlPoirier. I see that you changed the line width to 0.12mm in the most recent conventions, so I will also take that into account.

Eric

**Comment by CarlPoirier** [comment]
Awesome. Indeed this was one of the issues raised on the kicad forums in a thread about IPC compliance.

**Comment by swalense** [comment]
Hi @CarlPoirier,

I have made the changes to the footprints already in the PR in the last two commits.

Eric

**Comment by CarlPoirier** [comment]
Hi @swalense,

This is all great now, thanks for your contribution! I will be tagging the libraries for version 4.0.5 in a few hours so your changes will be included :)

**Comment by evanshultz** [comment]
I know this PR is closed, but there's an error in the silk for the SOT-353 footprint. I created PR #27 to correct it.

**Pull request merged**
