### PR TITLE
Add SC-82AA, SC-82AB, and ADI KS-4 packages

### PR DESCRIPTION
**Pull request by evanshultz**
Continuing from the discussion on issue #36, after more careful checking I realized SC-82 packages were rather different than the SOT-343/SC-70-4 in a number of ways. And the package for the ADI ADCMP35x I was after was different yet. So I just created all new footprints for them.

@jkriege2 @SchrodingersGat Maybe this isn't the best way to go. I'd appreciate feedback if combining packages into a single footprint is preferred.

Images:
image

Supporting docs:
https://www.pcb-3d.com/wordpress/wp-content/uploads/JEITA_ED-7500A_TC_TB_SC-1_TO_SC-88.pdf (page 165)
http://www.analog.com/media/en/technical-documentation/data-sheets/ADCMP350_354_356.pdf
http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/sc70ks/ks_4.pdf

### CODE REVIEW

**Comment by evanshultz** [comment]
Fixed courtyard. I think the remaining failures are either bogus or acceptable.

@jkriege2 @SchrodingersGat Do you have feedback on the footprints or the naming convention?

**Comment by SchrodingersGat** [comment]
I like the naming the way it is :)

**Comment by jkriege2** [comment]
I wouldn't know what ADI stands for ... if its analog devices ... write it out ...

**Comment by SchrodingersGat** [comment]
Yes if ADI stands for Analog Devices, please use the prefix `Analog_` as per the [FAQ](https://github.com/SchrodingersGat/kicad-library/wiki/FAQ#manufacturer-specific-footprints) ;)

**Comment by evanshultz** [comment]
Yes, ADI is for Analog Devices, Inc. I thought this was a common acronym. The front page of their website even refers to the company as ADI:
image

But sure, if that's the convention KiCad is using thanks for letting me know. Done.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
