### PR TITLE
adding VSON-8 package 3.3x3.3, pitch 0.65mm

### PR DESCRIPTION
**Pull request by jeromebeguin**
No better place to put this package.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @jeromebeguin I would suggest that this fits better under the https://github.com/KiCad/Housings_DFN_QFN.pretty lib?

**Comment by jeromebeguin** [comment]
It was @jkriege2  proposal. But if you think it's better to put it on Housings_DFN_QFN, it's fine for me. Let me know.

**Comment by SchrodingersGat** [comment]
@jkriege2 what do you think? SON is essential a DFN?

**Comment by jeromebeguin** [comment]
Why not creating a Housings_SON.pretty lib ?

**Comment by SchrodingersGat** [comment]
SON (Small Outline No-Lead) is an umbrella term that also includes DFN (Dual Flat No-Lead)

I propose that this is renamed to `DFN-8-1EP_3.3x3.3mm_Pitch0.65mm` and moved to https://github.com/KiCad/Housings_DFN_QFN.pretty

Also @jeromebeguin do you have a datasheet associated with this footprint? :)

**Comment by jeromebeguin** [comment]
Here is the datasheet I used: [CSD19537Q3](http://www.ti.com/lit/ds/symlink/csd19537q3.pdf)
I will also have to add: [TPS2561](http://www.ti.com/lit/ds/symlink/tps2561.pdf) it also has a VSON package but with 10 pins.

**Comment by SchrodingersGat** [comment]
@jeromebeguin ah, ok, my mistake this is not the same thing as an generic DFN at all. Apologies.

This is indeed the correct place for this one. I shall check it out soon :) 

Sorry for the mixup

**Comment by jeromebeguin** [comment]
Ok, good to know. I'm happy if we have found a solution. 

Thank you for the help.

**Comment by SchrodingersGat** [comment]
Ok @jeromebeguin I have finally had some time to look at this.

Generally speaking these footprints have been well made :) 

There are a few requirements to get them to conform to [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention).

(Did you know about the [KiCAD Library Utils](https://github.com/KiCad/kicad-library-utils) scripts which can help you to quickly check if your footprints match requirements? They are a great help!)

## VSON-10

1. Courtyard required - Please add a courtyard around the part. 0.05mm line with 0.25mm clearance (KLC 6.6/6.7)
1. Silkscreen pin-1 indication - we try to conform to the most recent IPC specs which are moving away from the "circle" to indicate pin 1. Instead, use a line that extends out past the pin (refer to my example image below).
1. Fab pin-1 indication - Please add a 1mm bevel to the top-left edge of the F.Fab markings to indicate package orientation. (Smaller than 1mm if needs to be, but in this case 1mm is good).
1. A simpler naming could be used here `VSON-10_3x3mm_Pitch0.5mm`. Any extra information should be added to the end of the name
1. Move text in "tighter" to the package to reduce space.

untitled

## VSON-8

1. I would suggest a simpler naming scheme e.g. `VSON-8_3.3x3.3mm_Pitch0.65mm`

Thanks for your work :) Very few changes and we should be good to merge.

**Comment by jeromebeguin** [comment]
Thank you for your feedback. For VSON-8, I would like to indicate clearly that Pins 5 to 9 are in short circuit. Do we have a general rules to indicate that in the component name ?

**Comment by SchrodingersGat** [comment]
That is a good question. I do not believe (I may be wrong) that we have an established convention for this. Perhaps @CarlPoirier  has seen this before, or @jkriege2 @diggit have an opinion?

You could always append "_NexFET" to the name as this is a very specific package.

**Comment by jkriege2** [comment]
I would name all connected pads the same, as e.g. here:
2017-02-06 18_35_40-footprint editor no active library

JAN

**Comment by jeromebeguin** [comment]
it means I will have to modify the CSD19537Q3 schematics as well.

**Comment by jkriege2** [comment]
I would say so, as it does not make too much sense (IMHO) to have Pins implicitly connected in a footprint, but not explicitly in the schematic ... i.e. you don't see what you actually put to the board in the schmatic ...

Best,
JAN

**Comment by jeromebeguin** [comment]
Perfect, it's fine for me. I'll do the modification on both later today.

**Comment by SchrodingersGat** [comment]
Our [KLC Scripts](https://github.com/KiCad/kicad-library-utils) give the following errors:

```
checking module: VSON-10-Th_11SC_3x3mm_Pitch0.5mm
  Violating Rule 10.4
    Value has a height of 1mm, thickness of 0.15mm, is filled with footprint name and is placed on the
    fabrication layer.
      Contents of value label ('VSON-10_3x3mm_Pitch0.5mm_ThermalPad') is different from module name
      'VSON-10-Th_11SC_3x3mm_Pitch0.5mm'!
      
checking module: VSON-8_3.3x3.3mm_Pitch0.65mm_NexFET
  Violating Rule 10.8
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
      3D model filename 'VSON-8-Th_5-9SC_3.3x3.3mm_Pitch0.65mm' is different from footprint name
      'VSON-8_3.3x3.3mm_Pitch0.65mm_NexFET'!
```

**Comment by jeromebeguin** [comment]
Could you check this PR and merge it if it's ok ?

**Comment by jkriege2** [comment]
Please fix:
- silkscreen is under package ...
- add %R-label to F.Fab
- courtyard is too close at top/bottom (should be 0.25mm measured from package outline)
- courtyard is too far from left/right (should be 0.25mm from pad-outline

best,
JAN

**Comment by jeromebeguin** [comment]
I still have an error with the F.CrtYd on VSON-10 but I've check and it's 0.25mm from pad border. So don't understand the error.

**Comment by jkriege2** [comment]
Old script version in Travis ... or rather a bugfixe has not been merged yet ;-) ... if it's OK (looking at it) it should be fine!

JAN

**Comment by jkriege2** [comment]
Hi!

I checked you footprints again:
1. `VSON-8_3.3x3.3mm_Pitch0.65mm_NexFET`: OK
2. `VSON-10_3x3mm_Pitch0.5mm_ThermalPad` some last changes please:
  2.1. please change name to `VSON-10-1EP_3x3mm_Pitch0.5mm_ThermalPad` in accordance with the symbols in e.g. https://github.com/KiCad/Housings_SSOP.pretty
  2.2. You made thermal vias into the pad, but there is no copper on the bottom. I think if there are thermal vias, you should also have a bottom-copper-pad that at least covers them (i.e. 2.4x1.65mm) ... otherwise it's not clear to me why you should have thermal vias ...

Please fix those so we can merge ...

Best,
JAN

**Comment by jkriege2** [comment]
Should this be part of https://github.com/KiCad/Housings_SON.pretty ???

**Comment by jeromebeguin** [comment]
Of course, but the repo wasn't existing when I created the part.

**Comment by jkriege2** [comment]
I know ... ;-)

I will close this PR!

**Pull request closed without merging**
